<div style="padding-bottom:10px;">
<!-- типу менюшка тре переробити -->
<a href="/types">Типи</a>
<a href="/statuses" style="padding-left:10px">Статуси</a>
<a href="/projects" style="padding-left:10px">Проекти</a>
<a href="/priorities" style="padding-left:10px">Приорітети</a>
</div>
<div style="padding-bottom:10px;">
<!-- типу корисна інформація - тре переробити -->
<select><option>Оберіть проект за замовчуванням</option></select><a href="/issue/add" style="padding-left:10px">Додати</a>
</div>
<div>
<!-- типу контейнер для багів -->
<?php
if (count($this->view->getVar('issues'))) {
	foreach ($this->view->getVar('issues') as $issue) {
		echo $issue->title;
	}
}
else {
?>
You have no issues! HURRAY!!!
<?php
}
?>
</div>
