-- MySQL Script generated by MySQL Workbench
-- 10/25/14 10:23:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `users_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_roles` ;

CREATE TABLE IF NOT EXISTS `users_roles` (
  `id` INT(10) NOT NULL,
  `role` VARCHAR(63) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

LOCK TABLES `users_roles` WRITE;
INSERT INTO `users_roles` VALUES (1,'Guest','Role with limited access. Could only view messages and has no access to pages which required authorization!'),(2,'User','Ordinary user. Administrator functions are disabled!'),(3,'Administrator','All features are available. No Restrictions are applied. Full access granted!!!');
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `salt` VARCHAR(22) NOT NULL,
  `active` INT(10) NULL,
  `created` INT(10) NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`, `role_id`),
  INDEX `fk_users_users_roles1_idx` (`role_id` ASC),
  CONSTRAINT `fk_users_users_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `users_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projects` ;

CREATE TABLE IF NOT EXISTS `projects` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `type` ;

CREATE TABLE IF NOT EXISTS `type` (
  `id` INT(10) NOT NULL,
  `project_id` INT(10) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_type_projects1_idx` (`project_id` ASC),
  CONSTRAINT `fk_type_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statuses` ;

CREATE TABLE IF NOT EXISTS `statuses` (
  `id` INT(10) NOT NULL,
  `project_id` INT(10) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_statuses_projects1_idx` (`project_id` ASC),
  CONSTRAINT `fk_statuses_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `issues` ;

CREATE TABLE IF NOT EXISTS `issues` (
  `id` INT(10) NOT NULL,
  `parent_id` INT(10) NOT NULL,
  `projects_id` INT(10) NOT NULL,
  `users_id` CHAR(32) NOT NULL,
  `type_id` INT(10) NOT NULL,
  `status_id` INT(10) NOT NULL,
  `title` VARCHAR(64) NOT NULL COMMENT '	',
  PRIMARY KEY (`id`, `projects_id`, `users_id`, `type_id`, `status_id`, `parent_id`),
  INDEX `fk_issues_projects_idx` (`projects_id` ASC),
  INDEX `fk_issues_users1_idx` (`users_id` ASC),
  INDEX `fk_issues_labels1_idx` (`type_id` ASC),
  INDEX `fk_issues_statuses1_idx` (`status_id` ASC),
  INDEX `fk_issues_issues1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_issues_projects`
    FOREIGN KEY (`projects_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_labels1`
    FOREIGN KEY (`type_id`)
    REFERENCES `type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_statuses1`
    FOREIGN KEY (`status_id`)
    REFERENCES `statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_issues1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_to_remember_me`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_to_remember_me` ;

CREATE TABLE IF NOT EXISTS `user_to_remember_me` (
  `id` INT(10) NOT NULL,
  `code` CHAR(32) NOT NULL,
  `last_updated` INT(10) NULL,
  PRIMARY KEY (`id`, `code`),
  INDEX `fk_user_to_remember_me_users1_idx` (`code` ASC),
  CONSTRAINT `fk_user_to_remember_me_users1`
    FOREIGN KEY (`code`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_emails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_emails` ;

CREATE TABLE IF NOT EXISTS `users_emails` (
  `id` INT(10) NOT NULL,
  `user_id` CHAR(32) NOT NULL,
  `email` VARCHAR(70) NULL,
  `is_primary` INT(1) NULL,
  `created` INT(10) NULL,
  `verified` INT(10) NULL,
  `deleted` INT(10) NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_users_emails_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_emails_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_verification_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_verification_codes` ;

CREATE TABLE IF NOT EXISTS `user_verification_codes` (
  `id` INT(10) NOT NULL,
  `email_id` INT(10) NOT NULL,
  `verification_code` VARCHAR(60) NOT NULL,
  `salt` VARCHAR(22) NOT NULL,
  `reason` ENUM('emailVerification', 'resetPassword') NOT NULL,
  `created` INT(10) NOT NULL,
  PRIMARY KEY (`id`, `email_id`),
  INDEX `fk_user_verification_codes_users_emails1_idx` (`email_id` ASC),
  CONSTRAINT `fk_user_verification_codes_users_emails1`
    FOREIGN KEY (`email_id`)
    REFERENCES `users_emails` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tags` ;

CREATE TABLE IF NOT EXISTS `tags` (
  `id` INT(10) NOT NULL,
  `project_id` INT(10) NOT NULL,
  `name` VARCHAR(64) NULL,
  `created` INT(10) NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_tags_projects1_idx` (`project_id` ASC),
  CONSTRAINT `fk_tags_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tags_to_issues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tags_to_issues` ;

CREATE TABLE IF NOT EXISTS `tags_to_issues` (
  `tag_id` INT(10) NOT NULL,
  `issue_id` INT(10) NOT NULL,
  PRIMARY KEY (`tag_id`, `issue_id`),
  INDEX `fk_tags_to_issues_issues1_idx` (`issue_id` ASC),
  CONSTRAINT `fk_tags_to_issues_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_to_issues_issues1`
    FOREIGN KEY (`issue_id`)
    REFERENCES `issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comments` ;

CREATE TABLE IF NOT EXISTS `comments` (
  `id` INT(10) NOT NULL,
  `issue_id` INT(10) NOT NULL,
  `description` TEXT NULL,
  `user_id` CHAR(32) NOT NULL,
  `created` INT(10) NULL,
  `system_text` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `user_id`, `issue_id`),
  INDEX `fk_comments_issues1_idx` (`issue_id` ASC),
  INDEX `fk_comments_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_comments_issues1`
    FOREIGN KEY (`issue_id`)
    REFERENCES `issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attachments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attachments` ;

CREATE TABLE IF NOT EXISTS `attachments` (
  `id` INT(10) NOT NULL,
  `comment_id` INT(10) NOT NULL,
  `type` VARCHAR(10) NULL,
  `name` VARCHAR(64) NULL,
  `size` INT(20) NULL,
  `replacedName` VARCHAR(64) NULL,
  `created` INT(10) NULL,
  PRIMARY KEY (`id`, `comment_id`),
  INDEX `fk_attachments_comments1_idx` (`comment_id` ASC),
  CONSTRAINT `fk_attachments_comments1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
